name: CI/CD

on:
  # Push on main excluding tags
  push:
    branches:
      - 'main'
    tags-ignore:
      - '*.*'

  # PR
  pull_request:
    branches:
      - 'main'

  # When a release is published
  release:
    types: [published]

  # Manual trigger
  workflow_dispatch:

jobs:

  build:
    name: CI/CD
    runs-on: ubuntu-latest

    steps:

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 and gradle cache
        id: java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Check if main repo
        id: is_main_repo
        run: |
          if [ $REPO_NAME == 'wborn/console-android' ]; then
            echo "value=true" >> $GITHUB_OUTPUT
          fi
        env:
          REPO_NAME: ${{ github.repository }}

      - name: Run assemble
        if: ${{ !steps.is_main_repo.outputs.value || github.event_name == 'pull_request' }}
        run: |
          cd GenericApp
          gradle assemble

      - name: Run assemble and publish snapshot
        if: ${{ steps.is_main_repo.outputs.value && github.event_name != 'release' && github.event_name != 'pull_request' }}
        run: |
          cd GenericApp
          gradle assemble publish -PsigningKey=$SIGNING_KEY -PsigningPassword=$SIGNING_PASSWORD -PpublishUsername=$MAVEN_USERNAME -PpublishPassword=$MAVEN_PASSWORD
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Run assemble and publish release
        if: ${{ steps.is_main_repo.outputs.value && github.event_name == 'release' }}
        run: |
          cd GenericApp
          gradle assemble publish -PappVersion=$MAVEN_TAG -PorlibVersion=$MAVEN_TAG -PsigningKey=$SIGNING_KEY -PsigningPassword=$SIGNING_PASSWORD -PpublishUsername=$MAVEN_USERNAME -PpublishPassword=$MAVEN_PASSWORD
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_TAG: ${{ github.ref_name }}

      - name: Upload build outputs
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: |
            **/build/outputs/**/*.aar
            **/build/outputs/**/*.apk
